// import React from 'react'
// import ReactDOM from 'react-dom/client'
// import App from './App.tsx'
// import './index.css'

// ReactDOM.createRoot(document.getElementById('root')!).render(
//   <React.StrictMode>
//     <App />
//   </React.StrictMode>,
// )


//entry point of your React application. It renders the App component into the browser.
//This code initializes the React app and connects it to the index.html file generated by React.
//The App component will hold the main structure of your application.


// Import React, which is used to build user interfaces.
import React from 'react';
//tool that connects app to the web page
import ReactDOM from 'react-dom/client';
// Import the main App component that contains your application.
import App from './App';
import './index.css';
//import awsExports from './aws-exports';
// import { Amplify } from 'aws-amplify';
//import { CognitoIdentityClient, GetIdCommand } from "@aws-sdk/client-cognito-identity";

//import { UserPool } from 'aws-cdk-lib/aws-cognito';
//import awsExports from "./aws-exports";

//console.log("awsExports:",awsExports);




 //Initialize Amplify with correct configuration
 // This connects the app to AWS Cognito for user authentication.
//  Amplify.configure({//The Amplify.configure() method links the React application to AWS Cognito.
//   Auth: {
//     Cognito:{
//       userPoolId: "us-east-1_ZgdHinkjc",
//       userPoolClientId: "d71lh69j33ljq911jr33sbukp",
//       loginWith:{
//         email:true,
//       },
//       //signUpVerificationMethod: "code",
//       userAttributes:{
//         email:{
//           required:true,
//         },
//       },
//       //mandatorySignIn: true,// all users must sign in to use the app.
//       selfSignUpEnabled: true, 
      
//     },
//   },
  
// });
//

 //here=>
 //Amplify.configure({
  //Auth:{
  // Cognito:{
   //   userPoolId: "us-east-1_ZgdHinkjc", // Replace with User Pool ID from output
    //  userPoolClientId: "d71lh69j33ljq911jr33sbukp", // Replace with App Client ID from output
     // loginWith:{
      //  email:true,
      //},
      //signUpVerificationMethod: "code",
      //userAttributes:{
       // email:{
        //  required:true,
        //},
      //},
      //allowGuestAccess:false,
      //passwordFormat:{
      //  minLength:8,
       // requireLowercase: true,
        //requireUppercase: true,
        //requireNumbers: true,
        //requireSpecialCharacters: true,
      //},

    //},
  //},
//});

// Render the App component inside the HTML element with ID "root".
//This connects the React app (App component) to the <div id="root"> element in the index.html file.=Where on the webpage should I put my app
ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
 